name: Build Dotnet

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  BUILD_CONFIG: Release

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        rid: [win-x64, win-arm64, linux-x64]
        self: [--no-self-contained, --self-contained]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
        with:
          dotnet-version: 7.0
      - name: dotnet build
        run: dotnet build -c ${{ env.BUILD_CONFIG }}
      - name: dotnet publish
        run: dotnet publish -c ${{ env.BUILD_CONFIG }} -r ${{ matrix.rid }} ${{ matrix.self }}
      - uses: actions/upload-artifact@v3
        with:
          name: WpfApp-${{ matrix.rid }}${{ matrix.self }}
          path: ./src/LinuxBuild/WpfApp/bin/Release/net7.0-windows/${{ matrix.rid }}/publish/
